---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1801851/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH